# MAKEFILE FOR CAETE
    # Define the symbols we might want to change:
    FC	        := gfortran
    FCFLAGS     := -g -Wall -Warray-bounds
    SOURCES     := env5.f wbm4.f productivity1.f

    caete_env : $(SOURCES)
	$(FC) $(FCLAGS) $(SOURCES) -o caete_env.out




