/* File: carbonmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Fri Dec  2 14:36:47 2016
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *carbon_error;
static PyObject *carbon_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = carbon_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(prod,PROD)(float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC_US(carbon_hr,CARBON_HR)(float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(penman,PENMAN)(float*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(evpot2,EVPOT2)(float*,float*,float*,float*,float*);
extern void F_FUNC(tsoil,TSOIL)(float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ prod ************************************/
static char doc_f2py_rout_carbon_prod[] = "\
ph,ar,nppa,laia,f5 = prod(temp,p0,w,wmax,ca,ipar)\n\nWrapper for ``prod``.\
\n\nParameters\n----------\n"
"temp : input float\n"
"p0 : input float\n"
"w : input float\n"
"wmax : input float\n"
"ca : input float\n"
"ipar : input float\n"
"\nReturns\n-------\n"
"ph : float\n"
"ar : float\n"
"nppa : float\n"
"laia : float\n"
"f5 : float";
/* extern void F_FUNC(prod,PROD)(float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_carbon_prod(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float temp = 0;
  PyObject *temp_capi = Py_None;
  float p0 = 0;
  PyObject *p0_capi = Py_None;
  float w = 0;
  PyObject *w_capi = Py_None;
  float wmax = 0;
  PyObject *wmax_capi = Py_None;
  float ca = 0;
  PyObject *ca_capi = Py_None;
  float ipar = 0;
  PyObject *ipar_capi = Py_None;
  float ph = 0;
  float ar = 0;
  float nppa = 0;
  float laia = 0;
  float f5 = 0;
  static char *capi_kwlist[] = {"temp","p0","w","wmax","ca","ipar",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:carbon.prod",\
    capi_kwlist,&temp_capi,&p0_capi,&w_capi,&wmax_capi,&ca_capi,&ipar_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable laia */
  /* Processing variable w */
    f2py_success = float_from_pyobj(&w,w_capi,"carbon.prod() 3rd argument (w) can't be converted to float");
  if (f2py_success) {
  /* Processing variable wmax */
    f2py_success = float_from_pyobj(&wmax,wmax_capi,"carbon.prod() 4th argument (wmax) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ca */
    f2py_success = float_from_pyobj(&ca,ca_capi,"carbon.prod() 5th argument (ca) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ar */
  /* Processing variable nppa */
  /* Processing variable ph */
  /* Processing variable temp */
    f2py_success = float_from_pyobj(&temp,temp_capi,"carbon.prod() 1st argument (temp) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ipar */
    f2py_success = float_from_pyobj(&ipar,ipar_capi,"carbon.prod() 6th argument (ipar) can't be converted to float");
  if (f2py_success) {
  /* Processing variable p0 */
    f2py_success = float_from_pyobj(&p0,p0_capi,"carbon.prod() 2nd argument (p0) can't be converted to float");
  if (f2py_success) {
  /* Processing variable f5 */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&temp,&p0,&w,&wmax,&ca,&ipar,&ph,&ar,&nppa,&laia,&f5);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("fffff",ph,ar,nppa,laia,f5);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f5 */
  } /*if (f2py_success) of p0*/
  /* End of cleaning variable p0 */
  } /*if (f2py_success) of ipar*/
  /* End of cleaning variable ipar */
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
  /* End of cleaning variable ph */
  /* End of cleaning variable nppa */
  /* End of cleaning variable ar */
  } /*if (f2py_success) of ca*/
  /* End of cleaning variable ca */
  } /*if (f2py_success) of wmax*/
  /* End of cleaning variable wmax */
  } /*if (f2py_success) of w*/
  /* End of cleaning variable w */
  /* End of cleaning variable laia */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of prod ********************************/

/********************************* carbon_hr *********************************/
static char doc_f2py_rout_carbon_carbon_hr[] = "\
cl,cs,hr = carbon_hr(tsoil,f5,evap,laia)\n\nWrapper for ``carbon_hr``.\
\n\nParameters\n----------\n"
"tsoil : input float\n"
"f5 : input float\n"
"evap : input float\n"
"laia : input float\n"
"\nReturns\n-------\n"
"cl : float\n"
"cs : float\n"
"hr : float";
/* extern void F_FUNC_US(carbon_hr,CARBON_HR)(float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_carbon_carbon_hr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float tsoil = 0;
  PyObject *tsoil_capi = Py_None;
  float f5 = 0;
  PyObject *f5_capi = Py_None;
  float evap = 0;
  PyObject *evap_capi = Py_None;
  float laia = 0;
  PyObject *laia_capi = Py_None;
  float cl = 0;
  float cs = 0;
  float hr = 0;
  static char *capi_kwlist[] = {"tsoil","f5","evap","laia",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:carbon.carbon_hr",\
    capi_kwlist,&tsoil_capi,&f5_capi,&evap_capi,&laia_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable evap */
    f2py_success = float_from_pyobj(&evap,evap_capi,"carbon.carbon_hr() 3rd argument (evap) can't be converted to float");
  if (f2py_success) {
  /* Processing variable laia */
    f2py_success = float_from_pyobj(&laia,laia_capi,"carbon.carbon_hr() 4th argument (laia) can't be converted to float");
  if (f2py_success) {
  /* Processing variable tsoil */
    f2py_success = float_from_pyobj(&tsoil,tsoil_capi,"carbon.carbon_hr() 1st argument (tsoil) can't be converted to float");
  if (f2py_success) {
  /* Processing variable hr */
  /* Processing variable cl */
  /* Processing variable f5 */
    f2py_success = float_from_pyobj(&f5,f5_capi,"carbon.carbon_hr() 2nd argument (f5) can't be converted to float");
  if (f2py_success) {
  /* Processing variable cs */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&tsoil,&f5,&evap,&laia,&cl,&cs,&hr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("fff",cl,cs,hr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable cs */
  } /*if (f2py_success) of f5*/
  /* End of cleaning variable f5 */
  /* End of cleaning variable cl */
  /* End of cleaning variable hr */
  } /*if (f2py_success) of tsoil*/
  /* End of cleaning variable tsoil */
  } /*if (f2py_success) of laia*/
  /* End of cleaning variable laia */
  } /*if (f2py_success) of evap*/
  /* End of cleaning variable evap */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of carbon_hr ******************************/

/*********************************** penman ***********************************/
static char doc_f2py_rout_carbon_penman[] = "\
evap = penman(spre,temp,w,wmax,ur,rn,rc2)\n\nWrapper for ``penman``.\
\n\nParameters\n----------\n"
"spre : input float\n"
"temp : input float\n"
"w : input float\n"
"wmax : input float\n"
"ur : input float\n"
"rn : input float\n"
"rc2 : input float\n"
"\nReturns\n-------\n"
"evap : float";
/* extern void F_FUNC(penman,PENMAN)(float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_carbon_penman(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float spre = 0;
  PyObject *spre_capi = Py_None;
  float temp = 0;
  PyObject *temp_capi = Py_None;
  float w = 0;
  PyObject *w_capi = Py_None;
  float wmax = 0;
  PyObject *wmax_capi = Py_None;
  float ur = 0;
  PyObject *ur_capi = Py_None;
  float rn = 0;
  PyObject *rn_capi = Py_None;
  float rc2 = 0;
  PyObject *rc2_capi = Py_None;
  float evap = 0;
  static char *capi_kwlist[] = {"spre","temp","w","wmax","ur","rn","rc2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:carbon.penman",\
    capi_kwlist,&spre_capi,&temp_capi,&w_capi,&wmax_capi,&ur_capi,&rn_capi,&rc2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable evap */
  /* Processing variable ur */
    f2py_success = float_from_pyobj(&ur,ur_capi,"carbon.penman() 5th argument (ur) can't be converted to float");
  if (f2py_success) {
  /* Processing variable w */
    f2py_success = float_from_pyobj(&w,w_capi,"carbon.penman() 3rd argument (w) can't be converted to float");
  if (f2py_success) {
  /* Processing variable rn */
    f2py_success = float_from_pyobj(&rn,rn_capi,"carbon.penman() 6th argument (rn) can't be converted to float");
  if (f2py_success) {
  /* Processing variable wmax */
    f2py_success = float_from_pyobj(&wmax,wmax_capi,"carbon.penman() 4th argument (wmax) can't be converted to float");
  if (f2py_success) {
  /* Processing variable temp */
    f2py_success = float_from_pyobj(&temp,temp_capi,"carbon.penman() 2nd argument (temp) can't be converted to float");
  if (f2py_success) {
  /* Processing variable spre */
    f2py_success = float_from_pyobj(&spre,spre_capi,"carbon.penman() 1st argument (spre) can't be converted to float");
  if (f2py_success) {
  /* Processing variable rc2 */
    f2py_success = float_from_pyobj(&rc2,rc2_capi,"carbon.penman() 7th argument (rc2) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&spre,&temp,&w,&wmax,&ur,&rn,&rc2,&evap);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",evap);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of rc2*/
  /* End of cleaning variable rc2 */
  } /*if (f2py_success) of spre*/
  /* End of cleaning variable spre */
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
  } /*if (f2py_success) of wmax*/
  /* End of cleaning variable wmax */
  } /*if (f2py_success) of rn*/
  /* End of cleaning variable rn */
  } /*if (f2py_success) of w*/
  /* End of cleaning variable w */
  } /*if (f2py_success) of ur*/
  /* End of cleaning variable ur */
  /* End of cleaning variable evap */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of penman *******************************/

/*********************************** evpot2 ***********************************/
static char doc_f2py_rout_carbon_evpot2[] = "\
evap = evpot2(spre,temp,ur,rn)\n\nWrapper for ``evpot2``.\
\n\nParameters\n----------\n"
"spre : input float\n"
"temp : input float\n"
"ur : input float\n"
"rn : input float\n"
"\nReturns\n-------\n"
"evap : float";
/* extern void F_FUNC(evpot2,EVPOT2)(float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_carbon_evpot2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float spre = 0;
  PyObject *spre_capi = Py_None;
  float temp = 0;
  PyObject *temp_capi = Py_None;
  float ur = 0;
  PyObject *ur_capi = Py_None;
  float rn = 0;
  PyObject *rn_capi = Py_None;
  float evap = 0;
  static char *capi_kwlist[] = {"spre","temp","ur","rn",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:carbon.evpot2",\
    capi_kwlist,&spre_capi,&temp_capi,&ur_capi,&rn_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable evap */
  /* Processing variable ur */
    f2py_success = float_from_pyobj(&ur,ur_capi,"carbon.evpot2() 3rd argument (ur) can't be converted to float");
  if (f2py_success) {
  /* Processing variable rn */
    f2py_success = float_from_pyobj(&rn,rn_capi,"carbon.evpot2() 4th argument (rn) can't be converted to float");
  if (f2py_success) {
  /* Processing variable spre */
    f2py_success = float_from_pyobj(&spre,spre_capi,"carbon.evpot2() 1st argument (spre) can't be converted to float");
  if (f2py_success) {
  /* Processing variable temp */
    f2py_success = float_from_pyobj(&temp,temp_capi,"carbon.evpot2() 2nd argument (temp) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&spre,&temp,&ur,&rn,&evap);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",evap);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
  } /*if (f2py_success) of spre*/
  /* End of cleaning variable spre */
  } /*if (f2py_success) of rn*/
  /* End of cleaning variable rn */
  } /*if (f2py_success) of ur*/
  /* End of cleaning variable ur */
  /* End of cleaning variable evap */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of evpot2 *******************************/

/*********************************** tsoil ***********************************/
static char doc_f2py_rout_carbon_tsoil[] = "\
tsoil = tsoil(temp)\n\nWrapper for ``tsoil``.\
\n\nParameters\n----------\n"
"temp : input float\n"
"\nReturns\n-------\n"
"tsoil : float";
/* extern void F_FUNC(tsoil,TSOIL)(float*,float*); */
static PyObject *f2py_rout_carbon_tsoil(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float temp = 0;
  PyObject *temp_capi = Py_None;
  float tsoil = 0;
  static char *capi_kwlist[] = {"temp",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:carbon.tsoil",\
    capi_kwlist,&temp_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable tsoil */
  /* Processing variable temp */
    f2py_success = float_from_pyobj(&temp,temp_capi,"carbon.tsoil() 1st argument (temp) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&temp,&tsoil);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",tsoil);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of temp*/
  /* End of cleaning variable temp */
  /* End of cleaning variable tsoil */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of tsoil ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"prod",-1,{{-1}},0,(char *)F_FUNC(prod,PROD),(f2py_init_func)f2py_rout_carbon_prod,doc_f2py_rout_carbon_prod},
  {"carbon_hr",-1,{{-1}},0,(char *)F_FUNC_US(carbon_hr,CARBON_HR),(f2py_init_func)f2py_rout_carbon_carbon_hr,doc_f2py_rout_carbon_carbon_hr},
  {"penman",-1,{{-1}},0,(char *)F_FUNC(penman,PENMAN),(f2py_init_func)f2py_rout_carbon_penman,doc_f2py_rout_carbon_penman},
  {"evpot2",-1,{{-1}},0,(char *)F_FUNC(evpot2,EVPOT2),(f2py_init_func)f2py_rout_carbon_evpot2,doc_f2py_rout_carbon_evpot2},
  {"tsoil",-1,{{-1}},0,(char *)F_FUNC(tsoil,TSOIL),(f2py_init_func)f2py_rout_carbon_tsoil,doc_f2py_rout_carbon_tsoil},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "carbon",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_carbon(void) {
#else
#define RETVAL
PyMODINIT_FUNC initcarbon(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = carbon_module = PyModule_Create(&moduledef);
#else
  m = carbon_module = Py_InitModule("carbon", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module carbon (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'carbon' is auto-generated with f2py (version:2).\nFunctions:\n"
"  ph,ar,nppa,laia,f5 = prod(temp,p0,w,wmax,ca,ipar)\n"
"  cl,cs,hr = carbon_hr(tsoil,f5,evap,laia)\n"
"  evap = penman(spre,temp,w,wmax,ur,rn,rc2)\n"
"  evap = evpot2(spre,temp,ur,rn)\n"
"  tsoil = tsoil(temp)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  carbon_error = PyErr_NewException ("carbon.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));





/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"carbon");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
